### PR TITLE
Added CapIdealModuleBase

### PR DESCRIPTION
**Pull request by pvnbhargava**
In order to support the placement of ideal capacitors through schematic generators, we need a CapIdealModuleBase class. `database.py` already supports creation of a `cap_ideal` schematic template within BAG_prim, so I am following this convention.

### CODE REVIEW

**Comment by pkerichang** [comment]
Why can't you just instantiate a capacitor from analogLib, and set its capacitance value?  ResIdeal comes from a time when this capability does not exist, and now that I Think of it maybe I should just obsolete and remove it...

**Comment by pvnbhargava** [comment]
I haven't tried this yet, but are you saying you can call something like `self.instances['C0'].design(c=15e-15)` directly on an analogLib capacitor?

**Comment by pkerichang** [comment]
It's not design (since it is not a generator), but you can do:

Self.instances['c0'].parameters['c'] = '10f'

Assuming 'c' is the CDF parameter name.  Note that values should be string

**Comment by pvnbhargava** [comment]
Ah ok that makes sense, thanks!

**Pull request closed without merging**
